[dependencies]
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }

tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"

clap = { version = "4.5", features = ["derive"] }